# Generated by Django 5.0.6 on 2024-06-07 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('volumen', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('entregas', models.IntegerField(default=0)),
                ('estado_asignado', models.BooleanField(default=False)),
                ('carroceria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_carroceria_rel', to='transporte.carroceria')),
                ('ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_ciudad_destino_rel', to='general.ciudad')),
                ('ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_ciudad_origen_rel', to='general.ciudad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_usuario_rel', to=settings.AUTH_USER_MODEL)),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_usuario_asignado_rel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gen_solicitud',
            },
        ),
    ]
