# Generated by Django 5.0.6 on 2024-06-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carroceria',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
